export const studyStatus = {
  RECRUITING: 'recruiting',
  ACTIVE_NOT_RECRUITING: 'active_not_recruiting',
  COMPLETED: 'completed',
  ENROLLING: 'enrolling',
  NOT_YET_RECRUITING: 'not_yet_recruiting',
  SUSPENDED: 'suspended',
  TERMINATED: 'terminated',
  WITDRAWN: 'withdrawn',
  AVAILABLE: 'available',
  NO_LONGER_AVAILABLE: 'no_longer_available',
  TEMPORARY_NOT_AVAILABLE: 'temporarily_not_available',
  APPROVED_FOR_MARKETING: 'approved_for_marketing',
  WITHHELD: 'withheld',
  UNKNOWN: 'unknown',
};
